# Generated by Django 5.2 on 2025-04-17 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 4, 17, 18, 40, 25, 627187), verbose_name='Опубликована'),
        ),
    ]
