# Generated by Django 5.2 on 2025-04-25 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_blog_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descripiton',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 4, 25, 13, 18, 11, 318357), verbose_name='Опубликована'),
        ),
    ]
